name: SonarQube Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install SonarScanner
      run: |
        pip install sonar-scanner-cli

    - name: Run SonarQube Analysis
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.sources=. \
          -Dsonar.python.version=3.10 \
          -Dsonar.exclusions=tests/** \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
